#!/bin/bash
#
echo "sisesta ringi raadius"
read r
area=$(echo "scale=2;3.14 * ($r * $r)" | bc)
d=$(echo "scale=2;2 * $r"|bc)
circumference=$(echo "scale=2;3.14 * $d"| bc)

echo -n "Sinu ringi pindala on $area ruutsentimeetrit "
echo "ja ümbermõõt on $circumference"
