#!/bin/bash
#
echo -e "sisesta kuu number \c"
read kuu
if test $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12 # kuuvahemik
then
echo "Praegu on talv"
elif test $kuu -ge 3 -a $kuu -le 5 # kuuvahemik
then
echo "Praegu on kevad"
elif test $kuu -ge 6 -a $kuu -le 8 # kuuvahemik
then
echo "Praegu on suvi"
elif test $kuu -ge 9 -a $kuu -le 11 # kuuvahemik
then
echo "Praegu on sygis"
else
echo "Antud kuu nubmbrit pole"
fi
#
# skripti lopp
