#!/bin/bash
#
echo "sisesta oma vanus" #sisesta oma vanus
read vanus
if test $vanus -gt 0 -a $vanus -lt 11 #vanus suurem kui 0 ja suurem kui 11
then
echo "oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18 #vanus suurem kui 11 ja väiksem kui 18
then
echo "oled nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63 #vanus suuerm kui 18 ja väiksem kui 63
then
echo "oled täiskasvanu"
elif test $vanus -ge 63 #vanus suurem kui 63
then
echo "oled senjoor"
else
echo "vigane sisend"

fi
#
# skripti lõpp
