#!/bin/bash
#
aeg=$(date +%H) # aeg
nimi=$( whoami ) #kes ma olen
if [ $aeg -ge 6 -a $aeg -lt 12 ]; # ajavahemik
then
echo "Tere hommikust, $nimi!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; # ajavahemik
then
echo "Tere paevast, $nimi!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; # ajavahemik
then
echo "Tere ohtust, $nimi!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ]; # ajavahemik
then
echo "Head ood, $nimi!"
elif [ $aeg -ge 0 -a $aeg -lt 6 ]; # ajavahemik
then
echo "Head ood, $nimi!"
else
echo "vigane sisend"
fi
#
# skripti lopp
